In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
df=pd.read_csv("train.csv")

In [4]:
df.head()

id                                              title  Rating maincateg  \
0  16695  Fashionable & Comfortable Bellies For Women  (...     3.9     Women   
1   5120  Combo Pack of 4 Casual Shoes Sneakers For Men ...     3.8       Men   
2  18391         Cilia Mode Leo Sneakers For Women  (White)     4.4     Women   
3    495                            Men Black Sports Sandal     4.2       Men   
4  16408                            Men Green Sports Sandal     3.9       Men   

   platform  price1  actprice1 Offer %  norating1  noreviews1  star_5f  \
0  Flipkart     698        999  30.13%       38.0         7.0     17.0   
1  Flipkart     999       1999  50.03%      531.0        69.0    264.0   
2  Flipkart    2749       4999  45.01%       17.0         4.0     11.0   
3  Flipkart     518        724  15.85%    46413.0      6229.0   1045.0   
4  Flipkart    1379       2299  40.02%       77.0         3.0     35.0   

   star_4f  star_3f  star_2f  star_1f  fulfilled1  
0      9.0      6.0        3        3           0  
1     92.0     73.0       29       73           1  
2      3.0      2.0        1        0           1  
3  12416.0   5352.0      701     4595           1  
4     21.0      7.0        7        7           1

In [5]:
df.isna().sum()

id              0
title           0
Rating          0
maincateg     526
platform        0
price1          0
actprice1       0
Offer %         0
norating1     678
noreviews1    578
star_5f       588
star_4f       539
star_3f       231
star_2f         0
star_1f         0
fulfilled1      0
dtype: int64

In [6]:
df.nunique()

id            15730
title          4782
Rating           34
maincateg         2
platform          2
price1         1478
actprice1       885
Offer %        2530
norating1      2770
noreviews1     1122
star_5f        2196
star_4f        1448
star_3f        1107
star_2f         759
star_1f        1001
fulfilled1        2
dtype: int64

In [7]:
df.describe()

id        Rating        price1     actprice1      norating1  \
count  15730.000000  15730.000000  15730.000000  15730.000000   15052.000000   
mean   10479.541577      4.012873    688.070693   1369.286777    3057.660776   
std     6080.166276      0.298440    649.409586   1240.900227   11846.965689   
min        3.000000      0.000000     69.000000     42.000000       1.000000   
25%     5212.000000      3.900000    349.000000    699.000000      63.000000   
50%    10458.500000      4.000000    474.000000    999.000000     308.000000   
75%    15766.750000      4.200000    699.000000   1299.000000    1526.000000   
max    20973.000000      5.000000   5998.000000  13499.000000  289973.000000   

         noreviews1        star_5f       star_4f       star_3f       star_2f  \
count  15152.000000   15142.000000  15191.000000  15499.000000  15730.000000   
mean     423.976307    1585.239466    655.923310    357.260662    155.085188   
std     1768.230384    6177.476241   2855.735531   1402.246610    558.650254   
min        0.000000       0.000000      0.000000      0.000000      0.000000   
25%        9.000000      30.000000     12.000000      7.000000      3.000000   
50%       44.000000     150.000000     60.000000     34.000000     17.000000   
75%      215.000000     788.000000    300.000000    172.000000     77.000000   
max    45448.000000  151193.000000  74037.000000  34978.000000  11705.000000   

            star_1f    fulfilled1  
count  15730.000000  15730.000000  
mean     275.500572      0.601526  
std      958.589075      0.489600  
min        0.000000      0.000000  
25%        6.000000      0.000000  
50%       30.000000      1.000000  
75%      140.000000      1.000000  
max    18060.000000      1.000000

In [8]:
df.shape

(15730, 16)

In [9]:
df2=pd.read_csv("test.csv")
df2.shape

(5244, 14)

In [10]:
df3=pd.read_csv("Sample__submission.csv")
df3.shape

(5244, 2)

In [11]:
df2.isna().sum()

id              0
title           0
Rating        203
maincateg      67
platform        0
actprice1       0
norating1       0
noreviews1      0
star_5f        68
star_4f         0
star_3f         0
star_2f         0
star_1f       186
fulfilled1      0
dtype: int64

In [12]:
df2.head(5)

id                                              title  Rating maincateg  \
0   2242                            Casuals For Men  (Blue)     3.8       Men   
1  20532                           Women Black Flats Sandal     3.9     Women   
2  10648                           Women Gold Wedges Sandal     3.9     Women   
3  20677  Men's Height Increasing High Heel Formal Party...     3.9       Men   
4  12593                             Loafers For Men  (Tan)     3.9       Men   

   platform  actprice1  norating1  noreviews1  star_5f  star_4f  star_3f  \
0  Flipkart        999      27928        3543  14238.0     4295     3457   
1  Flipkart        499       3015         404   1458.0      657      397   
2  Flipkart        999        449          52    229.0       70       71   
3  Flipkart       2999        290          40    141.0       51       49   
4  Flipkart        999       2423         326   1265.0      414      293   

   star_2f  star_1f  fulfilled1  
0     1962   3976.0           1  
1      182    321.0           1  
2       33     46.0           1  
3       17     32.0           1  
4      143    308.0           0

In [13]:
df.head(5)

id                                              title  Rating maincateg  \
0  16695  Fashionable & Comfortable Bellies For Women  (...     3.9     Women   
1   5120  Combo Pack of 4 Casual Shoes Sneakers For Men ...     3.8       Men   
2  18391         Cilia Mode Leo Sneakers For Women  (White)     4.4     Women   
3    495                            Men Black Sports Sandal     4.2       Men   
4  16408                            Men Green Sports Sandal     3.9       Men   

   platform  price1  actprice1 Offer %  norating1  noreviews1  star_5f  \
0  Flipkart     698        999  30.13%       38.0         7.0     17.0   
1  Flipkart     999       1999  50.03%      531.0        69.0    264.0   
2  Flipkart    2749       4999  45.01%       17.0         4.0     11.0   
3  Flipkart     518        724  15.85%    46413.0      6229.0   1045.0   
4  Flipkart    1379       2299  40.02%       77.0         3.0     35.0   

   star_4f  star_3f  star_2f  star_1f  fulfilled1  
0      9.0      6.0        3        3           0  
1     92.0     73.0       29       73           1  
2      3.0      2.0        1        0           1  
3  12416.0   5352.0      701     4595           1  
4     21.0      7.0        7        7           1

In [14]:
df.drop('Offer %', axis = 1)

id                                              title  Rating  \
0      16695  Fashionable & Comfortable Bellies For Women  (...     3.9   
1       5120  Combo Pack of 4 Casual Shoes Sneakers For Men ...     3.8   
2      18391         Cilia Mode Leo Sneakers For Women  (White)     4.4   
3        495                            Men Black Sports Sandal     4.2   
4      16408                            Men Green Sports Sandal     3.9   
...      ...                                                ...     ...   
15725  16554                          Women Maroon Heels Sandal     4.3   
15726  19600                      Women Multicolor Flats Sandal     3.9   
15727   6733                            Women Navy Flats Sandal     3.7   
15728   3889                           Red Chief Men's Sneakers     3.9   
15729  13682                           Slip On For Men  (Brown)     5.0   

      maincateg  platform  price1  actprice1  norating1  noreviews1  star_5f  \
0         Women  Flipkart     698        999       38.0         7.0     17.0   
1           Men  Flipkart     999       1999      531.0        69.0    264.0   
2         Women  Flipkart    2749       4999       17.0         4.0     11.0   
3           Men  Flipkart     518        724    46413.0      6229.0   1045.0   
4           Men  Flipkart    1379       2299       77.0         3.0     35.0   
...         ...       ...     ...        ...        ...         ...      ...   
15725     Women  Flipkart     567       1199      807.0       114.0    485.0   
15726     Women  Flipkart     499        998      246.0        34.0    120.0   
15727     Women  Flipkart     329        499        NaN        18.0      NaN   
15728       Men    Amazon    2249       4499      750.0       479.0     13.0   
15729       Men  Flipkart    1539       2799        8.0         1.0      8.0   

       star_4f  star_3f  star_2f  star_1f  fulfilled1  
0          9.0      6.0        3        3           0  
1         92.0     73.0       29       73           1  
2          3.0      2.0        1        0           1  
3      12416.0   5352.0      701     4595           1  
4         21.0      7.0        7        7           1  
...        ...      ...      ...      ...         ...  
15725    177.0     61.0       41       43           0  
15726     45.0     37.0       16       28           1  
15727      NaN     20.0       10       15           1  
15728      6.0     10.0       25       47           1  
15729      0.0      0.0        0        0           1  

[15730 rows x 15 columns]

In [15]:
df_cat = pd.get_dummies(df['maincateg'])
df = pd.concat([df, df_cat], axis=1)
df_1 = pd.get_dummies(df['platform'])
df = pd.concat([df, df_1], axis=1)
df.head()

id                                              title  Rating maincateg  \
0  16695  Fashionable & Comfortable Bellies For Women  (...     3.9     Women   
1   5120  Combo Pack of 4 Casual Shoes Sneakers For Men ...     3.8       Men   
2  18391         Cilia Mode Leo Sneakers For Women  (White)     4.4     Women   
3    495                            Men Black Sports Sandal     4.2       Men   
4  16408                            Men Green Sports Sandal     3.9       Men   

   platform  price1  actprice1 Offer %  norating1  noreviews1  star_5f  \
0  Flipkart     698        999  30.13%       38.0         7.0     17.0   
1  Flipkart     999       1999  50.03%      531.0        69.0    264.0   
2  Flipkart    2749       4999  45.01%       17.0         4.0     11.0   
3  Flipkart     518        724  15.85%    46413.0      6229.0   1045.0   
4  Flipkart    1379       2299  40.02%       77.0         3.0     35.0   

   star_4f  star_3f  star_2f  star_1f  fulfilled1  Men  Women  Amazon  \
0      9.0      6.0        3        3           0    0      1       0   
1     92.0     73.0       29       73           1    1      0       0   
2      3.0      2.0        1        0           1    0      1       0   
3  12416.0   5352.0      701     4595           1    1      0       0   
4     21.0      7.0        7        7           1    1      0       0   

   Flipkart  
0         1  
1         1  
2         1  
3         1  
4         1

In [16]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df1 = le.fit_transform(df.title)
df1

array([1313,  845,  728, ..., 4343, 3066, 3421])

In [17]:
df4=pd.DataFrame(df1,columns=['new_title'])
df4

new_title
0           1313
1            845
2            728
3           2125
4           2195
...          ...
15725       4325
15726       4333
15727       4343
15728       3066
15729       3421

[15730 rows x 1 columns]

In [18]:
df = pd.concat([df, df4], axis = 1)
df.head()

id                                              title  Rating maincateg  \
0  16695  Fashionable & Comfortable Bellies For Women  (...     3.9     Women   
1   5120  Combo Pack of 4 Casual Shoes Sneakers For Men ...     3.8       Men   
2  18391         Cilia Mode Leo Sneakers For Women  (White)     4.4     Women   
3    495                            Men Black Sports Sandal     4.2       Men   
4  16408                            Men Green Sports Sandal     3.9       Men   

   platform  price1  actprice1 Offer %  norating1  noreviews1  ...  star_4f  \
0  Flipkart     698        999  30.13%       38.0         7.0  ...      9.0   
1  Flipkart     999       1999  50.03%      531.0        69.0  ...     92.0   
2  Flipkart    2749       4999  45.01%       17.0         4.0  ...      3.0   
3  Flipkart     518        724  15.85%    46413.0      6229.0  ...  12416.0   
4  Flipkart    1379       2299  40.02%       77.0         3.0  ...     21.0   

   star_3f  star_2f  star_1f  fulfilled1  Men  Women  Amazon  Flipkart  \
0      6.0        3        3           0    0      1       0         1   
1     73.0       29       73           1    1      0       0         1   
2      2.0        1        0           1    0      1       0         1   
3   5352.0      701     4595           1    1      0       0         1   
4      7.0        7        7           1    1      0       0         1   

   new_title  
0       1313  
1        845  
2        728  
3       2125  
4       2195  

[5 rows x 21 columns]

In [20]:
df.drop(['maincateg','platform' , 'title', 'Offer %'], axis = 1,inplace=True)
df.head(5)

id  Rating  price1  actprice1  norating1  noreviews1  star_5f  star_4f  \
0  16695     3.9     698        999       38.0         7.0     17.0      9.0   
1   5120     3.8     999       1999      531.0        69.0    264.0     92.0   
2  18391     4.4    2749       4999       17.0         4.0     11.0      3.0   
3    495     4.2     518        724    46413.0      6229.0   1045.0  12416.0   
4  16408     3.9    1379       2299       77.0         3.0     35.0     21.0   

   star_3f  star_2f  star_1f  fulfilled1  Men  Women  Amazon  Flipkart  \
0      6.0        3        3           0    0      1       0         1   
1     73.0       29       73           1    1      0       0         1   
2      2.0        1        0           1    0      1       0         1   
3   5352.0      701     4595           1    1      0       0         1   
4      7.0        7        7           1    1      0       0         1   

   new_title  
0       1313  
1        845  
2        728  
3       2125  
4       2195

In [21]:
df.isnull().sum()

id              0
Rating          0
price1          0
actprice1       0
norating1     678
noreviews1    578
star_5f       588
star_4f       539
star_3f       231
star_2f         0
star_1f         0
fulfilled1      0
Men             0
Women           0
Amazon          0
Flipkart        0
new_title       0
dtype: int64

In [22]:
df = df.fillna(df.mean())

In [24]:
df.isnull().sum()

id            0
Rating        0
price1        0
actprice1     0
norating1     0
noreviews1    0
star_5f       0
star_4f       0
star_3f       0
star_2f       0
star_1f       0
fulfilled1    0
Men           0
Women         0
Amazon        0
Flipkart      0
new_title     0
dtype: int64

In [201]:
x = df.drop(['price1','id','new_title','fulfilled1'], axis = 1)
y = df.price1

In [202]:
x.shape

(15730, 13)

In [203]:
y.shape

(15730,)

In [204]:
from sklearn.preprocessing import StandardScaler
s1 = StandardScaler()
x_scaled = s1.fit_transform(x)
x_scaled

array([[-0.37822407, -0.29841122, -0.26057498, ...,  0.88958851,
        -0.14885793,  0.14885793],
       [-0.71331079,  0.50748096, -0.21803263, ..., -1.12411523,
        -0.14885793,  0.14885793],
       [ 1.29720951,  2.9251575 , -0.26238713, ...,  0.88958851,
        -0.14885793,  0.14885793],
       ...,
       [-1.0483975 , -0.70135731,  0.        , ...,  0.88958851,
        -0.14885793,  0.14885793],
       [-0.37822407,  2.52221141, -0.19913451, ..., -1.12411523,
         6.71781454, -6.71781454],
       [ 3.3077298 ,  1.1521947 , -0.26316376, ..., -1.12411523,
        -0.14885793,  0.14885793]])

In [205]:
x_scaled.shape

(15730, 13)

In [170]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.33)

In [206]:
from sklearn.model_selection import train_test_split
x_train_scaled, x_test_scaled, y_train, y_test = train_test_split(x_scaled, y, test_size=0.33)

In [207]:
from sklearn.linear_model import LinearRegression
m1 = LinearRegression()

In [208]:
m1.fit(x_train_scaled, y_train)

LinearRegression()

In [209]:
m1.score(x_test_scaled, y_test)

0.8147436403106773

In [212]:
y_preds=m1.predict(x_test_scaled)
y_preds

array([ 587.83985171,  610.1874273 ,  522.72429668, ..., 1927.05200527,
       2137.9983152 ,  520.55515527])

In [245]:
ndf1 = pd.read_csv('test.csv')
ndf1.head(3)

id                     title  Rating maincateg  platform  actprice1  \
0   2242   Casuals For Men  (Blue)     3.8       Men  Flipkart        999   
1  20532  Women Black Flats Sandal     3.9     Women  Flipkart        499   
2  10648  Women Gold Wedges Sandal     3.9     Women  Flipkart        999   

   norating1  noreviews1  star_5f  star_4f  star_3f  star_2f  star_1f  \
0      27928        3543  14238.0     4295     3457     1962   3976.0   
1       3015         404   1458.0      657      397      182    321.0   
2        449          52    229.0       70       71       33     46.0   

   fulfilled1  
0           1  
1           1  
2           1

In [246]:
ndf1_cat = pd.get_dummies(ndf1['maincateg'])
ndf2 = pd.concat([ndf1, ndf1_cat], axis=1)
ndf2.head()
ndf3 = pd.get_dummies(ndf2['platform'])
ndf4 = pd.concat([ndf2, ndf3], axis=1)
ndf4.head(3)

id                     title  Rating maincateg  platform  actprice1  \
0   2242   Casuals For Men  (Blue)     3.8       Men  Flipkart        999   
1  20532  Women Black Flats Sandal     3.9     Women  Flipkart        499   
2  10648  Women Gold Wedges Sandal     3.9     Women  Flipkart        999   

   norating1  noreviews1  star_5f  star_4f  star_3f  star_2f  star_1f  \
0      27928        3543  14238.0     4295     3457     1962   3976.0   
1       3015         404   1458.0      657      397      182    321.0   
2        449          52    229.0       70       71       33     46.0   

   fulfilled1  Men  Women  Amazon  Flipkart  
0           1    1      0       0         1  
1           1    0      1       0         1  
2           1    0      1       0         1

In [247]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
ndf5 = le.fit_transform(ndf4.title)
ndf5

array([ 322, 2068, 2140, ..., 2148, 2283, 2309])

In [248]:
ndf6 = pd.DataFrame(ndf5, columns =['new_ntitle'])
ndf6.head()

new_ntitle
0         322
1        2068
2        2140
3        1224
4        1048

In [249]:
ndf7 = pd.concat([ndf4, ndf6], axis = 1)
ndf7.head(3)

id                     title  Rating maincateg  platform  actprice1  \
0   2242   Casuals For Men  (Blue)     3.8       Men  Flipkart        999   
1  20532  Women Black Flats Sandal     3.9     Women  Flipkart        499   
2  10648  Women Gold Wedges Sandal     3.9     Women  Flipkart        999   

   norating1  noreviews1  star_5f  star_4f  star_3f  star_2f  star_1f  \
0      27928        3543  14238.0     4295     3457     1962   3976.0   
1       3015         404   1458.0      657      397      182    321.0   
2        449          52    229.0       70       71       33     46.0   

   fulfilled1  Men  Women  Amazon  Flipkart  new_ntitle  
0           1    1      0       0         1         322  
1           1    0      1       0         1        2068  
2           1    0      1       0         1        2140

In [251]:
ieds=ndf7.id
ndf8 = ndf7.drop(['maincateg','platform' , 'title','new_ntitle','fulfilled1','id'], axis = 1)


In [252]:
ndf8.shape

(5244, 13)

In [264]:
ieds2=pd.DataFrame(ieds,columns=['id'])
ieds2.head(3)

id
0   2242
1  20532
2  10648

In [254]:
ndf8.head(3)

Rating  actprice1  norating1  noreviews1  star_5f  star_4f  star_3f  \
0     3.8        999      27928        3543  14238.0     4295     3457   
1     3.9        499       3015         404   1458.0      657      397   
2     3.9        999        449          52    229.0       70       71   

   star_2f  star_1f  Men  Women  Amazon  Flipkart  
0     1962   3976.0    1      0       0         1  
1      182    321.0    0      1       0         1  
2       33     46.0    0      1       0         1

In [255]:
ndf8.isnull().sum()

Rating        203
actprice1       0
norating1       0
noreviews1      0
star_5f        68
star_4f         0
star_3f         0
star_2f         0
star_1f       186
Men             0
Women           0
Amazon          0
Flipkart        0
dtype: int64

In [256]:
ndf8['Rating'] = ndf8['Rating'].fillna(ndf8['Rating'].mean())
ndf8['star_5f'] = ndf8['star_5f'].fillna(ndf8['star_5f'].mean())
ndf8['star_1f'] = ndf8['star_1f'].fillna(ndf8['star_1f'].mean())

In [257]:
ndf8.isnull().sum()

Rating        0
actprice1     0
norating1     0
noreviews1    0
star_5f       0
star_4f       0
star_3f       0
star_2f       0
star_1f       0
Men           0
Women         0
Amazon        0
Flipkart      0
dtype: int64

In [258]:
ndf8_train_scaled = s1.fit_transform(ndf8)

In [259]:
z = m1.predict(ndf8_train_scaled)
z

array([456.23475509, 268.59672837, 487.90590298, ..., 470.90290661,
       260.66392895, 621.31067071])

In [260]:
one_submission = pd.DataFrame(z, columns = ['price1'])
one_submission.head()

price1
0   456.234755
1   268.596728
2   487.905903
3  1384.713609
4   507.897226

In [265]:
list1 = []
for i in ieds2.index:
    list1.append(ieds2['id'][i])

mk = pd.DataFrame(list1, columns = ['id'])

In [266]:
two_submissions = pd.concat([mk,one_submission], axis = 1)
two_submissions.head()

id       price1
0   2242   456.234755
1  20532   268.596728
2  10648   487.905903
3  20677  1384.713609
4  12593   507.897226

In [267]:
two_submissions.shape

(5244, 2)

In [268]:
two_submissions.to_csv(('two_submissions.csv'), header = True, index = False)